#define CS_HS_INTENTION 0x00

#define CS_STATUS_REQ 0x00
#define CS_STATUS_PING 0x01
#define SC_STATUS_RES 0x00
#define SC_STATUS_PONG 0x01

#define CS_LOGIN_HELLO 0x00
#define CS_LOGIN_KEY 0x01 
#define CS_LOGIN_CUSTOM_QUERY_ANSWER 0x02 
#define CS_LOGIN_LOGIN_ACKNOWLEDGED 0x03 
#define CS_LOGIN_COOKIE_RESPONSE 0x04 

#define SC_LOGIN_DISCONNECT 0x00
#define SC_LOGIN_HELLO 0x01
#define SC_LOGIN_FINISHED 0x02
#define SC_LOGIN_COMPRESSION 0x03
#define SC_LOGIN_CUSTOM_QUERY 0x04
#define SC_LOGIN_COOKIE_REQUEST 0x05
